from pathlib import Path
import environ
env = environ.Env()
environ.Env.read_env()
"""
Django settings for kelassorAdvanced project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6e39_tl6iki@!b%3ek_8aei778(&_glsb)8z7v2ouvc0$cd#d*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_extensions',
    'user',
    'courses',
    'payments',
    'tickets',
    'discounts',
    'core',
    'django.contrib.sites',  # برای پشتیبانی از allauth
    'allauth',
    
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # برای ورود با گوگل
    'allauth.socialaccount.providers.facebook',  # برای ورود با فیس‌بوک
]




SITE_ID = 1  # برای سیستم Site Framework Django

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Custom user model
AUTH_USER_MODEL = 'user.CustomUser'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.example.com')  # آدرس سرور SMTP
EMAIL_PORT = env('EMAIL_PORT', default=587)  # پورت SMTP
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)  # استفاده از TLS
# ایمیل ارسال‌کننده
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='your_email@example.com')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD',
                          default='your_email_password')  # رمز عبور ایمیل
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@kelassor.com')

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Frontend Address
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # احراز هویت پیش‌فرض
    ),
}


ROOT_URLCONF = 'kelassorAdvanced.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kelassorAdvanced.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# settings.py

# تنظیمات ورود با گوگل
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'your_google_client_id'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'your_google_client_secret'

# تنظیمات ورود با فیس‌بوک
SOCIAL_AUTH_FACEBOOK_KEY = 'your_facebook_app_id'
SOCIAL_AUTH_FACEBOOK_SECRET = 'your_facebook_app_secret'

# settings.py

# تنظیمات مرتبط با حساب کاربری (برای تایید ایمیل و دیگر موارد)
# جایگزینی ACCOUNT_EMAIL_REQUIRED با ACCOUNT_SIGNUP_FIELDS جدید
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # تایید ایمیل الزامی است

# تنظیمات برای ورود اجتماعی و نمایش دکمه‌ها
SOCIALACCOUNT_LOGIN_ON_GET = True  # ورود خودکار پس از ثبت‌نام
SOCIALACCOUNT_EMAIL_REQUIRED = True  # ایمیل در هنگام ثبت‌نام الزامی است

SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapters.DefaultSocialAccountAdapter'
SOCIALACCOUNT_QUERY_EMAIL = True  # ایمیل را از طریق ورود اجتماعی درخواست کنید

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
# RabbitMQ simple connection URL (برای تست مستقیم با pika)
RABBITMQ_URL = "amqp://guest:guest@localhost:5672/"
RABBITMQ_DEFAULT_QUEUE = "app_events"

# تنظیمات Celery
CELERY_BROKER_URL = 'pyamqp://guest@localhost//'  # برای اتصال به RabbitMQ
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'rpc://'  # برای ذخیره‌سازی نتایج تسک‌ها
CELERY_TIMEZONE = 'Asia/Tehran'  # زمان‌بندی تسک‌ها با توجه به منطقه زمانی ایران

